version: "3.8"

services:
  socrates-buddy:
    build: .
    ports:
      - "7860:7860"
    environment:
      # Only pass the sensitive API keys from .env
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    env_file:
      - .env
